version: 0.3.{build}
image: Visual Studio 2017
dotnet_csproj:
  version: "{version}"
  package_version: "{version}"
before_build:
  # - choco install "msbuild-sonarqube-runner" -y
  - dotnet restore
build:
  verbosity: normal
after_build:
  - dotnet pack KohonenNetwork -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: 4HWYue95aIcpxcp09bhEMf+3D6JHfKP+dQbSxf5ba0FvN1NK+3W7KWKi0YZZBjAd
  artifact: /.*\.nupkg/
  on:
    branch: master